import { Inter } from 'next/font/google'
import { cookies } from 'next/headers'
import type { Metadata } from 'next'

import './globals.css'
import 'react-toastify/dist/ReactToastify.css'

import AuthProvider from '@/context/AuthProvider'
import ToastProvider from '@/context/ToastProvider'
import Sidebar from '@/components/sidebar/Sidebar'
import dashboardApiRequest from '@/http-request/fetch/dashboards'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Sixpack',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const sessionToken = cookies().get('sessionToken')?.value
  const dashboards = await dashboardApiRequest.getAll()

  return (
    <html lang="en">
      <head>
        <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet" />
      </head>
      <body className={inter.className}>
        <AuthProvider initialToken={sessionToken ?? ''}>
          <div className="flex">
            {sessionToken && <Sidebar dashboards={dashboards.dashboards} />}
            <div className="flex-1">{children}</div>
          </div>
          <ToastProvider />
        </AuthProvider>
      </body>
    </html>
  )
}
