import { Inter } from 'next/font/google'
import { cookies } from 'next/headers'

import type { Metadata } from 'next'
import './globals.css'
import AuthProvider from '@/context/AuthProvider'
import ToastProvider from '@/context/ToastProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Sixpack',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const sessionToken = cookies().get('sessionToken')?.value

  return (
    <html lang="en">
      <head>
        <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet" />
      </head>
      <body className={inter.className}>
        <AuthProvider initialToken={sessionToken ?? ''}>
          {children}
          <ToastProvider />
        </AuthProvider>
      </body>
    </html>
  )
}
